apiVersion: v1
kind: Namespace
metadata:
  name: gitops

---
# docker.io
apiVersion: v1
kind: Secret
metadata:
  namespace: gitops
  name: docker-io-creds
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJnaW5lcyIsInBhc3N3b3JkIjoiZzFuY09sZG9jayIsImVtYWlsIjoiZ2luZXMuY29sbGFkb0BnbWFpbC5jb20iLCJhdXRoIjoiWjJsdVpYTTZaekZ1WTA5c1pHOWphdz09In19fQ==

---
# nexus local
apiVersion: v1
kind: Secret
metadata:
  namespace: gitops
  name: nexus-local-creds
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICIxOTIuMTY4LjEwMC4xMzo4MDgzIjogewogICAgICAiZW1haWwiOiAiZ2luZXMuY29sbGFkb0BnbWFpbC5jb20iLAogICAgICAiYXV0aCI6ICJZV1J0YVc0NloybHVZMjlzTURFPSIKICAgIH0KICB9Cn0K

---
# gitlab local
apiVersion: v1
kind: Secret
metadata:
  namespace: gitops
  name: git-local-creds
  annotations:
    tekton.dev/git-0: http://192.168.100.13
type: kubernetes.io/basic-auth
stringData:
  username: gines
  password: gincol01

---
# gitlab local secret webhook
apiVersion: v1
kind: Secret
metadata:
  namespace: gitops
  name: gitlab-interceptor-secret
type: Opaque
stringData:
  secretToken: "hGxVaHn6XAnoR-Jb9FTi"

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitops-serviceaccount
  namespace: gitops
secrets:
  - name: docker-io-creds
  - name: nexus-local-creds
  - name: git-local-creds
  - name: gitlab-interceptor-secret

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: gitops-api-access
rules:
  - apiGroups:
      - ""
      - apps
      - autoscaling
      - batch
      - extensions
      - policy
      - rbac.authorization.k8s.io
      - triggers.tekton.dev
      - tekton.dev
      - k8s.nginx.org
    resources:
      - componentstatuses
      - configmaps
      - daemonsets
      - deployments
      - events
      - endpoints
      - horizontalpodautoscalers
      - ingress
      - jobs
      - limitranges
      - namespaces
      - nodes
      - pods
      - persistentvolumes
      - persistentvolumeclaims
      - resourcequotas
      - replicasets
      - replicationcontrollers
      - serviceaccounts
      - services
      - eventlisteners
      - triggerbindings
      - triggertemplates
      - triggers
      - pipelineruns
      - pipelineresources
      - taskruns
      - clustertriggerbindings
      - clusterinterceptors
      - virtualservers
      - virtualserverroutes
    verbs: ["*"]
  - nonResourceURLs: ["*"]
    verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitops-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gitops-api-access
subjects:
- kind: ServiceAccount
  name: gitops-serviceaccount
  namespace: gitops
