apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "samplechart.fullname" . }}
  namespace: {{ include "samplechart.namespace" . }}
  labels:
    {{- include "samplechart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "samplechart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "samplechart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: {{ .Values.deploy.port }}
                {{- with .Values.environmentVars }}
              protocol: TCP
          {{- end }}
