apiVersion: v1
kind: Service
metadata:
  name: {{ include "samplechart.fullname" . }}
  namespace: {{ include "samplechart.namespace" . }}
  labels:
    {{- include "samplechart.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.deploy.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "samplechart.selectorLabels" . | nindent 4 }}
